title: Nikita Patil # your name (or website title) here
logo: "images/WhatsApp Image 2020-02-08 at 9.26.29 AM (1).jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Data Analyst
  <br>
   
  M.S. information Technology and Management.
  <br>
  <a href="https://www.linkedin.com/in/nikita-nitin-patil/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

